#!/usr/bin/env python


class SecurityGroupEgress():

    def __init__(self):
        self.ruleList = [] 

    def addRule(self, ipProtocol="", cidrIp=""):
        ruleDictionary = {"IpProtocol" : ipProtocol, "CidrIp" : cidrIp}
        self.ruleList.append(ruleDictionary)
    
    def toList(self):
        return self.ruleList
