# Copyright (c) 2012-2026, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.
#
# *** Do not modify - this file is autogenerated ***


from . import AWSObject, AWSProperty, PropsDictType, Tags


class ApprovalConfiguration(AWSProperty):
    """
    `ApprovalConfiguration <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registry-approvalconfiguration.html>`__
    """

    props: PropsDictType = {
        "AutoApprovalRules": ([str], False),
    }


class ClaimMatchValueType(AWSProperty):
    """
    `ClaimMatchValueType <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registry-claimmatchvaluetype.html>`__
    """

    props: PropsDictType = {
        "MatchValueString": (str, False),
        "MatchValueStringList": ([str], False),
    }


class AuthorizingClaimMatchValueType(AWSProperty):
    """
    `AuthorizingClaimMatchValueType <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registry-authorizingclaimmatchvaluetype.html>`__
    """

    props: PropsDictType = {
        "ClaimMatchOperator": (str, True),
        "ClaimMatchValue": (ClaimMatchValueType, True),
    }


class CustomClaimValidationType(AWSProperty):
    """
    `CustomClaimValidationType <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registry-customclaimvalidationtype.html>`__
    """

    props: PropsDictType = {
        "AuthorizingClaimMatchValue": (AuthorizingClaimMatchValueType, True),
        "InboundTokenClaimName": (str, True),
        "InboundTokenClaimValueType": (str, True),
    }


class CustomJWTAuthorizerConfiguration(AWSProperty):
    """
    `CustomJWTAuthorizerConfiguration <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registry-customjwtauthorizerconfiguration.html>`__
    """

    props: PropsDictType = {
        "AllowedAudience": ([str], False),
        "AllowedClients": ([str], False),
        "AllowedScopes": ([str], False),
        "CustomClaims": ([CustomClaimValidationType], False),
        "DiscoveryUrl": (str, True),
    }


class AuthorizerConfiguration(AWSProperty):
    """
    `AuthorizerConfiguration <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registry-authorizerconfiguration.html>`__
    """

    props: PropsDictType = {
        "CustomJWTAuthorizer": (CustomJWTAuthorizerConfiguration, True),
    }


class DiscoveryConfiguration(AWSProperty):
    """
    `DiscoveryConfiguration <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registry-discoveryconfiguration.html>`__
    """

    props: PropsDictType = {
        "AuthorizerConfiguration": (AuthorizerConfiguration, False),
    }


class Registry(AWSObject):
    """
    `Registry <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-agentregistry-registry.html>`__
    """

    resource_type = "AWS::AgentRegistry::Registry"

    props: PropsDictType = {
        "ApprovalConfiguration": (ApprovalConfiguration, False),
        "AuthorizerType": (str, False),
        "Description": (str, False),
        "DiscoveryConfiguration": (DiscoveryConfiguration, False),
        "Name": (str, True),
        "Tags": (Tags, False),
    }


class RegistryRecordIamCredentialProvider(AWSProperty):
    """
    `RegistryRecordIamCredentialProvider <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-registryrecordiamcredentialprovider.html>`__
    """

    props: PropsDictType = {
        "Region": (str, False),
        "RoleArn": (str, False),
        "Service": (str, False),
    }


class RegistryRecordOAuthCredentialProvider(AWSProperty):
    """
    `RegistryRecordOAuthCredentialProvider <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-registryrecordoauthcredentialprovider.html>`__
    """

    props: PropsDictType = {
        "CustomParameters": (dict, False),
        "GrantType": (str, False),
        "ProviderArn": (str, True),
        "Scopes": ([str], False),
    }


class RegistryRecordCredentialProviderUnion(AWSProperty):
    """
    `RegistryRecordCredentialProviderUnion <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-registryrecordcredentialproviderunion.html>`__
    """

    props: PropsDictType = {
        "IamCredentialProvider": (RegistryRecordIamCredentialProvider, False),
        "OauthCredentialProvider": (RegistryRecordOAuthCredentialProvider, False),
    }


class RegistryRecordCredentialProviderConfiguration(AWSProperty):
    """
    `RegistryRecordCredentialProviderConfiguration <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-registryrecordcredentialproviderconfiguration.html>`__
    """

    props: PropsDictType = {
        "CredentialProvider": (RegistryRecordCredentialProviderUnion, True),
        "CredentialProviderType": (str, True),
    }


class DescriptorSourceFromUrl(AWSProperty):
    """
    `DescriptorSourceFromUrl <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-descriptorsourcefromurl.html>`__
    """

    props: PropsDictType = {
        "CredentialProviderConfigurations": (
            [RegistryRecordCredentialProviderConfiguration],
            False,
        ),
        "Url": (str, True),
    }


class DescriptorSource(AWSProperty):
    """
    `DescriptorSource <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-descriptorsource.html>`__
    """

    props: PropsDictType = {
        "FromUrl": (DescriptorSourceFromUrl, False),
    }


class A2aAgentCardDescriptor(AWSProperty):
    """
    `A2aAgentCardDescriptor <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-a2aagentcarddescriptor.html>`__
    """

    props: PropsDictType = {
        "Data": (str, False),
        "DataSchemaVersion": (str, False),
        "Source": (DescriptorSource, False),
    }


class SourceOnlyDescriptorSourceFromUrl(AWSProperty):
    """
    `SourceOnlyDescriptorSourceFromUrl <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-sourceonlydescriptorsourcefromurl.html>`__
    """

    props: PropsDictType = {
        "Url": (str, True),
    }


class SourceOnlyDescriptorSource(AWSProperty):
    """
    `SourceOnlyDescriptorSource <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-sourceonlydescriptorsource.html>`__
    """

    props: PropsDictType = {
        "FromUrl": (SourceOnlyDescriptorSourceFromUrl, False),
    }


class AgUiDescriptor(AWSProperty):
    """
    `AgUiDescriptor <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-aguidescriptor.html>`__
    """

    props: PropsDictType = {
        "Source": (SourceOnlyDescriptorSource, False),
    }


class SkillMdSourceFromUrl(AWSProperty):
    """
    `SkillMdSourceFromUrl <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-skillmdsourcefromurl.html>`__
    """

    props: PropsDictType = {
        "Url": (str, True),
    }


class SkillMdSource(AWSProperty):
    """
    `SkillMdSource <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-skillmdsource.html>`__
    """

    props: PropsDictType = {
        "FromUrl": (SkillMdSourceFromUrl, False),
    }


class AgentSkillsMdDescriptor(AWSProperty):
    """
    `AgentSkillsMdDescriptor <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-agentskillsmddescriptor.html>`__
    """

    props: PropsDictType = {
        "Data": (str, False),
        "DataSchemaVersion": (str, False),
        "Source": (SkillMdSource, False),
    }


class AgentSkillsAdditionalData(AWSProperty):
    """
    `AgentSkillsAdditionalData <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-agentskillsadditionaldata.html>`__
    """

    props: PropsDictType = {
        "SkillMd": (AgentSkillsMdDescriptor, False),
    }


class AgentSkillsDefinitionDescriptor(AWSProperty):
    """
    `AgentSkillsDefinitionDescriptor <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-agentskillsdefinitiondescriptor.html>`__
    """

    props: PropsDictType = {
        "AdditionalData": (AgentSkillsAdditionalData, False),
        "Data": (str, False),
        "DataSchemaVersion": (str, False),
    }


class CustomDescriptor(AWSProperty):
    """
    `CustomDescriptor <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-customdescriptor.html>`__
    """

    props: PropsDictType = {
        "Data": (str, False),
    }


class HttpDescriptor(AWSProperty):
    """
    `HttpDescriptor <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-httpdescriptor.html>`__
    """

    props: PropsDictType = {
        "Source": (SourceOnlyDescriptorSource, False),
    }


class McpToolsDescriptor(AWSProperty):
    """
    `McpToolsDescriptor <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-mcptoolsdescriptor.html>`__
    """

    props: PropsDictType = {
        "Data": (str, False),
        "DataSchemaVersion": (str, False),
    }


class McpServerAdditionalData(AWSProperty):
    """
    `McpServerAdditionalData <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-mcpserveradditionaldata.html>`__
    """

    props: PropsDictType = {
        "Tools": (McpToolsDescriptor, False),
    }


class McpServerDescriptor(AWSProperty):
    """
    `McpServerDescriptor <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-mcpserverdescriptor.html>`__
    """

    props: PropsDictType = {
        "AdditionalData": (McpServerAdditionalData, False),
        "Data": (str, False),
        "DataSchemaVersion": (str, False),
        "Source": (DescriptorSource, False),
    }


class Descriptors(AWSProperty):
    """
    `Descriptors <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-descriptors.html>`__
    """

    props: PropsDictType = {
        "A2aAgentCard": (A2aAgentCardDescriptor, False),
        "AgentSkillsDefinition": (AgentSkillsDefinitionDescriptor, False),
        "Agui": (AgUiDescriptor, False),
        "Custom": (CustomDescriptor, False),
        "Http": (HttpDescriptor, False),
        "McpServer": (McpServerDescriptor, False),
    }


class RegistryRecord(AWSObject):
    """
    `RegistryRecord <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-agentregistry-registryrecord.html>`__
    """

    resource_type = "AWS::AgentRegistry::RegistryRecord"

    props: PropsDictType = {
        "Description": (str, False),
        "Descriptors": (Descriptors, True),
        "DisplayName": (str, False),
        "Name": (str, True),
        "RecordType": (str, True),
        "RecordVersion": (str, False),
        "RegistryId": (str, False),
        "Tags": (Tags, False),
    }
