# Copyright (c) 2012-2026, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.
#
# *** Do not modify - this file is autogenerated ***


from . import AWSObject, AWSProperty, PropsDictType, Tags


class BillScenario(AWSObject):
    """
    `BillScenario <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-bcmpricingcalculator-billscenario.html>`__
    """

    resource_type = "AWS::BcmPricingCalculator::BillScenario"

    props: PropsDictType = {
        "CostCategoryGroupSharingPreferenceArn": (str, False),
        "ExpiresAt": (str, False),
        "GroupSharingPreference": (str, False),
        "Name": (str, False),
        "Tags": (Tags, False),
    }


class BillInterval(AWSProperty):
    """
    `BillInterval <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-bcmpricingcalculator-billscenario-billinterval.html>`__
    """

    props: PropsDictType = {
        "End": (str, False),
        "Start": (str, False),
    }
