# Copyright (c) 2012-2026, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.
#
# *** Do not modify - this file is autogenerated ***


from . import AWSObject, AWSProperty, PropsDictType
from .validators import integer


class Dictionary(AWSObject):
    """
    `Dictionary <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elementalinference-dictionary.html>`__
    """

    resource_type = "AWS::ElementalInference::Dictionary"

    props: PropsDictType = {
        "Entries": (str, False),
        "Language": (str, True),
        "Name": (str, True),
        "Tags": (dict, False),
    }


class DataSourceConfiguration(AWSProperty):
    """
    `DataSourceConfiguration <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elementalinference-feed-datasourceconfiguration.html>`__
    """

    props: PropsDictType = {
        "FixtureId": (str, True),
    }


class ClippingConfig(AWSProperty):
    """
    `ClippingConfig <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elementalinference-feed-clippingconfig.html>`__
    """

    props: PropsDictType = {
        "CallbackMetadata": (str, False),
        "DataSourceConfiguration": (DataSourceConfiguration, False),
    }


class TemplateGroup(AWSProperty):
    """
    `TemplateGroup <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elementalinference-feed-templategroup.html>`__
    """

    props: PropsDictType = {
        "Name": (str, True),
        "TemplateUris": ([str], True),
    }


class CroppingConfig(AWSProperty):
    """
    `CroppingConfig <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elementalinference-feed-croppingconfig.html>`__
    """

    props: PropsDictType = {
        "TemplateGroups": ([TemplateGroup], False),
    }


class AspectRatio(AWSProperty):
    """
    `AspectRatio <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elementalinference-feed-aspectratio.html>`__
    """

    props: PropsDictType = {
        "Height": (integer, True),
        "Width": (integer, True),
    }


class SubtitlingConfig(AWSProperty):
    """
    `SubtitlingConfig <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elementalinference-feed-subtitlingconfig.html>`__
    """

    props: PropsDictType = {
        "AspectRatio": (AspectRatio, False),
        "Dictionary": (str, False),
        "Language": (str, True),
        "ProfanityFilter": (str, False),
    }


class OutputConfig(AWSProperty):
    """
    `OutputConfig <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elementalinference-feed-outputconfig.html>`__
    """

    props: PropsDictType = {
        "Clipping": (ClippingConfig, False),
        "Cropping": (CroppingConfig, False),
        "Subtitling": (SubtitlingConfig, False),
    }


class GetOutput(AWSProperty):
    """
    `GetOutput <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elementalinference-feed-getoutput.html>`__
    """

    props: PropsDictType = {
        "Description": (str, False),
        "Name": (str, True),
        "OutputConfig": (OutputConfig, True),
        "Status": (str, True),
    }


class Feed(AWSObject):
    """
    `Feed <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elementalinference-feed.html>`__
    """

    resource_type = "AWS::ElementalInference::Feed"

    props: PropsDictType = {
        "AccessRoleArn": (str, False),
        "Name": (str, True),
        "Outputs": ([GetOutput], True),
        "Tags": (dict, False),
    }
