# Copyright (c) 2012-2021, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.
#
# *** Do not modify - this file is autogenerated ***
# Resource specification version: 39.7.0


from troposphere import Tags

from . import AWSObject
from .validators import integer


class InferenceScheduler(AWSObject):
    resource_type = "AWS::LookoutEquipment::InferenceScheduler"

    props = {
        "DataDelayOffsetInMinutes": (integer, False),
        "DataInputConfiguration": (dict, True),
        "DataOutputConfiguration": (dict, True),
        "DataUploadFrequency": (str, True),
        "InferenceSchedulerName": (str, False),
        "ModelName": (str, True),
        "RoleArn": (str, True),
        "ServerSideKmsKeyId": (str, False),
        "Tags": (Tags, False),
    }
