# Copyright (c) 2012-2026, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.
#
# *** Do not modify - this file is autogenerated ***


from . import AWSObject, PropsDictType


class ImageSet(AWSObject):
    """
    `ImageSet <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-medicalimaging-imageset.html>`__
    """

    resource_type = "AWS::MedicalImaging::ImageSet"

    props: PropsDictType = {
        "DatastoreId": (str, False),
    }
