# Copyright (c) 2012-2025, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.
#
# *** Do not modify - this file is autogenerated ***


from . import AWSObject, AWSProperty, PropsDictType
from .validators import integer


class EncryptionConfiguration(AWSProperty):
    """
    `EncryptionConfiguration <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3vectors-vectorbucket-encryptionconfiguration.html>`__
    """

    props: PropsDictType = {
        "KmsKeyArn": (str, False),
        "SseType": (str, False),
    }


class MetadataConfiguration(AWSProperty):
    """
    `MetadataConfiguration <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3vectors-index-metadataconfiguration.html>`__
    """

    props: PropsDictType = {
        "NonFilterableMetadataKeys": ([str], False),
    }


class Index(AWSObject):
    """
    `Index <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3vectors-index.html>`__
    """

    resource_type = "AWS::S3Vectors::Index"

    props: PropsDictType = {
        "DataType": (str, True),
        "Dimension": (integer, True),
        "DistanceMetric": (str, True),
        "EncryptionConfiguration": (EncryptionConfiguration, False),
        "IndexName": (str, False),
        "MetadataConfiguration": (MetadataConfiguration, False),
        "VectorBucketArn": (str, False),
        "VectorBucketName": (str, False),
    }


class VectorBucket(AWSObject):
    """
    `VectorBucket <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3vectors-vectorbucket.html>`__
    """

    resource_type = "AWS::S3Vectors::VectorBucket"

    props: PropsDictType = {
        "EncryptionConfiguration": (EncryptionConfiguration, False),
        "VectorBucketName": (str, False),
    }


class VectorBucketPolicy(AWSObject):
    """
    `VectorBucketPolicy <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3vectors-vectorbucketpolicy.html>`__
    """

    resource_type = "AWS::S3Vectors::VectorBucketPolicy"

    props: PropsDictType = {
        "Policy": (dict, True),
        "VectorBucketArn": (str, False),
        "VectorBucketName": (str, False),
    }
