# Copyright (c) 2012-2026, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.
#
# *** Do not modify - this file is autogenerated ***


from . import AWSObject, AWSProperty, PropsDictType
from .validators import integer


class Quota(AWSObject):
    """
    `Quota <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicequotas-quota.html>`__
    """

    resource_type = "AWS::ServiceQuotas::Quota"

    props: PropsDictType = {
        "QuotaCode": (str, False),
        "ServiceCode": (str, False),
    }


class MetricInfo(AWSProperty):
    """
    `MetricInfo <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-servicequotas-quota-metricinfo.html>`__
    """

    props: PropsDictType = {
        "MetricDimensions": (dict, False),
        "MetricName": (str, False),
        "MetricNamespace": (str, False),
        "MetricStatisticRecommendation": (str, False),
    }


class QuotaContextInfo(AWSProperty):
    """
    `QuotaContextInfo <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-servicequotas-quota-quotacontextinfo.html>`__
    """

    props: PropsDictType = {
        "ContextId": (str, False),
        "ContextScope": (str, False),
        "ContextScopeType": (str, False),
    }


class QuotaPeriod(AWSProperty):
    """
    `QuotaPeriod <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-servicequotas-quota-quotaperiod.html>`__
    """

    props: PropsDictType = {
        "PeriodUnit": (str, False),
        "PeriodValue": (integer, False),
    }
