# Copyright (c) 2012-2026, Mark Peek <mark@peek.org>
# All rights reserved.
#
# See LICENSE file for full license.
#
# *** Do not modify - this file is autogenerated ***


from . import AWSObject, AWSProperty, PropsDictType, Tags


class SoftwareSet(AWSObject):
    """
    `SoftwareSet <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-thinclient-softwareset.html>`__
    """

    resource_type = "AWS::ThinClient::SoftwareSet"

    props: PropsDictType = {
        "Tags": (Tags, False),
    }


class Software(AWSProperty):
    """
    `Software <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-thinclient-softwareset-software.html>`__
    """

    props: PropsDictType = {
        "Name": (str, False),
        "Version": (str, False),
    }
