name: "Copilot Setup Steps"
on:
  workflow_dispatch:
  push:
    branches:
      - feature/*
jobs:
  setup-copilot-steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          npm install
          npx pyright --version
          python -m pip install -r requirements-dev.txt
          make spec
          make regen
          make test
          make lint